
GET http://localhost:3000/api/produtos
#####
POST http://localhost:3000/api/produtos
Content-Type: application/json

{
  "nome": "Cadeira Gamer",
  "preco": 850.50,
  "quantidade": 2
}
###
POST http://localhost:3000/api/produtos
{
  "nome": "Cadeira Gamer",
  "preco": 850.50,
  "quantidade": 2
}